FORMAT: 1A
HOST: http://openbloodstocks.herokuapp.com

# OpenBloodStocks

# Group Blood Types
Notes related resources of the **Blood Types API**

## Notes Collection [/blood_types]
### List all blood types [GET]
+ Response 200 (application/json)

        [{"id":1,"name":"Apos"},{"id":2,"name":"Aneg"},{"id":3,"name":"Bpos"},{"id":4,"name":"Bneg"},{"id":5,"name":"Opos"},{"id":6,"name":"Oneg"},{"id":7,"name":"ABpos"},{"id":8,"name":"ABneg"}]

# Group Records
Records related resources of the **Records API**

## Records [/records]
### List all records [GET]
+ Parameters
    + authority (required, string) ... Name of the blood donation authority

+ Response 200 (application/json)
